version: '3.9'

services:
  app:
    container_name: testing-app
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default
  
  db:
    container_name: testing-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "dev_testing"
      MYSQL_USER: "dev_testing"
      MYSQL_PASSWORD: "dev_testing"
      MYSQL_DATABASE: "dev_testing"
    volumes:
      - ./docker/mysql/dev_testing.sql:/docker-entrypoint-initdb.d/dev_testing.sql
    networks:
      - default
    ports:
      - 3306:3306

  pma:
    container_name: testing-pma
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    networks:
      - default
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

networks:
  default:
    name: testing-network_default
    driver: bridge